POST  http://localhost:5000/api/comment/newcomment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzZiMjg1MDA4ZTE2YjM0ZWYxNTk2MTMiLCJpYXQiOjE2NjkyMDg0MTMsImV4cCI6MTY2OTQ2NzYxM30.2EO6l-1NdR5I-WaD3tAO0yvcdeiJgxCHiVWwPfelNkk

{
    "text":"Không spam dc bài olaf nữa r :(",
    "postId":"6334f7c3392aefeca1ca0a65"
}

###
PUT http://localhost:5000/api/comment/633a90f6f2689050ba815913
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI5ZTFmMjM2MDhhM2E4MGM5NmFlYTMiLCJpYXQiOjE2NjQ3ODI0MDYsImV4cCI6MTY2NTA0MTYwNn0.bf8AZOLzMEqnt6AVzSavXdeVwNwaht04_aLgbEmMgEg

{
    "text":"Không spam dc bài đồ long nữa r :("
}

###
DELETE http://localhost:5000/api/comment/633a9205b82d4db73cf6fc12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI5ZTFmMjM2MDhhM2E4MGM5NmFlYTMiLCJpYXQiOjE2NjQ3ODI0MDYsImV4cCI6MTY2NTA0MTYwNn0.bf8AZOLzMEqnt6AVzSavXdeVwNwaht04_aLgbEmMgEg


###
GET http://localhost:5000/api/comment?postId=6334f7c3392aefeca1ca0a65