POST http://localhost:5000/api/feeling/createFeeling
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzZiMjg1MDA4ZTE2YjM0ZWYxNTk2MTMiLCJpYXQiOjE2NjkxMjcyNTMsImV4cCI6MTY2OTM4NjQ1M30.OWfrO5tkStYKOT_QPe0G_szk9fh7L5AZ6LrZKzzf6gA

{
    "type":"like",
    "postId":"6334f7c3392aefeca1ca0a65"
}
###

GET http://localhost:5000/api/feeling/checkfeeling/?postId=6334f7c3392aefeca1ca0a65
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzZiMjg1MDA4ZTE2YjM0ZWYxNTk2MTMiLCJpYXQiOjE2NjkxMjcyNTMsImV4cCI6MTY2OTM4NjQ1M30.OWfrO5tkStYKOT_QPe0G_szk9fh7L5AZ6LrZKzzf6gA
