POST http://localhost:5000/api/feeling/createFeeling
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI4MDU5NzRjNDliY2M0OTUwNTRkMGYiLCJpYXQiOjE2NjgwNDY5NjksImV4cCI6MTY2ODMwNjE2OX0.3QmS9YXSA-n_ltZU4IyHjSikWxIhL7RYsgcuf4B_gNs

{
    "type":"like",
    "postId":"632beb6a22c0a7dd279e95d1"
}
###

GET http://localhost:5000/api/feeling/checkfeeling
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI4MDU5NzRjNDliY2M0OTUwNTRkMGYiLCJpYXQiOjE2NjgwNDY5NjksImV4cCI6MTY2ODMwNjE2OX0.3QmS9YXSA-n_ltZU4IyHjSikWxIhL7RYsgcuf4B_gNs

{
   "postId": "6334f7c3392aefeca1ca0a65"
}