POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"username2",
    "password":"1234567"
}

###
GET http://localhost:5000/api/user/632b02ad070d6e22ac8cb371


###
GET http://localhost:5000/api/user/get-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI4MDU5NzRjNDliY2M0OTUwNTRkMGYiLCJpYXQiOjE2NjQyNDA5OTksImV4cCI6MTY2NDUwMDE5OX0.SYQL2MA3_RbCzv7HaVqB6iBh_2aw8dys_NwY_dJ_1zU


###
Get  http://localhost:5000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI4MDU5NzRjNDliY2M0OTUwNTRkMGYiLCJpYXQiOjE2NjM1OTg1Mzh9._PCr04GFyxCyJezJnwAkufq9okLe5K1lYZDSnY0KsJg