POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"tuananh",
    "password":"1234567"
}

###
GET http://localhost:5000/api/user/632b02ad070d6e22ac8cb371


###
GET http://localhost:5000/api/user/get-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI4MDU5NzRjNDliY2M0OTUwNTRkMGYiLCJpYXQiOjE2NjM3NDk0MzUsImV4cCI6MTY2NDAwODYzNX0.6wZ93eM5xyphsA_x6owvj5O2Ngfr30f72LxH2Vz9qRs


###
Get  http://localhost:5000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI4MDU5NzRjNDliY2M0OTUwNTRkMGYiLCJpYXQiOjE2NjM1OTg1Mzh9._PCr04GFyxCyJezJnwAkufq9okLe5K1lYZDSnY0KsJg