PUT http://localhost:5000/api/user/update-password/6329e1f23608a3a80c96aea3
Content-Type: application/json

{
    "username":"username3",
    "currentPassword":"1234567",
    "newPassword":"newPassword"
}

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI5ZTFmMjM2MDhhM2E4MGM5NmFlYTMiLCJpYXQiOjE2NjM2ODkyNjUsImV4cCI6MTY2Mzk0ODQ2NX0.Y_ZgapaD0noVK9V9ktaoF8rb9b8I-RnxtMKI80v16nY

###
POST http://localhost:5000/api/user/newuser
